namespace CoreCheat_Reborn.CheatClasses
{
    class Enums
    {
        public enum Bones
        {
            HEAD = 8,
            NECK = 7,
            BODY = 6,
            RIGHT_HAND = 39,
            LEFT_HAND = 13,
            RIGHT_LEG = 73,
            LEFT_LEG = 66,
            RIGHT_FOOT = 74,
            LEFT_FOOT = 67
        }
        public enum Teams
        {
            NONE = 0,
            SPECTATOR,
            TERRORIST,
            ANTI_TERRORIST
        }
        public enum VisualColor
        {
            ENGINE = 0,
            REDBLUE,
            HEALTH
        }
        public enum  BunnyType
        {
            NORMAL = 0,
            STRAFE
        }
        public enum GlowType
        {
            NORMAL,
            MOVING,
            FROZEN,
            BREATHING
        }
        public enum GlowStyle
        {
            NORMAL,
            BLOOM
        }
        public enum FlagState
        {
            NULL = 0,
            ONAIR = 256,
            ONGROUND = 257,
            AIRMOVING = 258,
            GROUNDMOVING = 259,
            TOAIRCROUCH = 260,
            TOCROUCH = 261,
            AIRCROUCH = 262,
            CROUCHING = 263,
            INWATER = 1280,
            INPUDDLE = 1281,
            WATERCROUCH = 1286,
            PUDDLECROUCH = 1287
        }
        public enum KeysList
        {
            E,
            X,
            V,
            Z,
            NOKEYS
        }
        public enum ShootState
        {
            SHOOT = 1,
            STOP = 4
        }
        public enum MoveState
        {
            MAKEMOVE = 6
        }
        public enum GameState
        {
            NONE = 0,
            CHALLENGE,
            CONNECTED,
            NEW,
            PRESPAWN,
            SPAWN,
            FULL,
            CHANGELEVEL
        }
        public enum SpectatorView
        {
            FIRSTPERSON = 0,
            DEATHCAM = 1,
            FREEZECAM = 2,
            FIXED = 3,
            EGO = 4,
            THIRDPERSON = 5,
            FREE = 6
        }
        public enum ScopeLevels
        {
            NOTSCOPED,
            LEVEL1,
            LEVEL2
        }
        public enum ViewModel
        {
            NOMODEL = 0,
            T_HAND = 60
        }
        public enum PerformanceTimes
        {
            VHIGH,
            HIGH = 1,
            NORMAL = 20,
            MEDIUM = 50,
            LOW = 100,
            VERYLOW = 120,
            TRASH = 150
        }
        public enum BeepVoice
        {
            Default = 440,
            HIGHFREQ = 600,
            LOWFREQ = 400,
            DURATION = 250
        }
        public enum EntityQuality
        {
            NORMAL = 0,
            GENUİNE,
            VİNTAGE,
            UNUSUAL,
            COMMUNİTY = 5,
            DEVELOPER,
            SELFMADE,
            CUSTOMİZED,
            STRANGE,
            COMPLETED,
            TOURNAMENT = 12,
        }
        public enum ClassID
        {
            CAI_BaseNPC = 0,
            CAK47,
            CBaseAnimating,
            CBaseAnimatingOverlay,
            CBaseAttributableItem,
            CBaseButton,
            CBaseCombatCharacter,
            CBaseCombatWeapon,
            CBaseCSGrenade,
            CBaseCSGrenadeProjectile,
            CBaseDoor,
            CBaseEntity,
            CBaseFlex,
            CBaseGrenade,
            CBaseParticleEntity,
            CBasePlayer,
            CBasePropDoor,
            CBaseTeamObjectiveResource,
            CBaseTempEntity,
            CBaseToggle,
            CBaseTrigger,
            CBaseViewModel,
            CBaseVPhysicsTrigger,
            CBaseWeaponWorldModel,
            CBeam,
            CBeamSpotlight,
            CBoneFollower,
            CBRC4Target,
            CBreachCharge,
            CBreachChargeProjectile,
            CBreakableProp,
            CBreakableSurface,
            CBumpMine,
            CBumpMineProjectile,
            CC4,
            CCascadeLight,
            CChicken,
            CColorCorrection,
            CColorCorrectionVolume,
            CCSGameRulesProxy,
            CCSPlayer,
            CCSPlayerResource,
            CCSRagdoll,
            CCSTeam,
            CDangerZone,
            CDangerZoneController,
            CDEagle,
            CDecoyGrenade,
            CDecoyProjectile,
            CDrone,
            CDronegun,
            CDynamicLight,
            CDynamicProp,
            CEconEntity,
            CEconWearable,
            CEmbers,
            CEntityDissolve,
            CEntityFlame,
            CEntityFreezing,
            CEntityParticleTrail,
            CEnvAmbientLight,
            CEnvDetailController,
            CEnvDOFController,
            CEnvGasCanister,
            CEnvParticleScript,
            CEnvProjectedTexture,
            CEnvQuadraticBeam,
            CEnvScreenEffect,
            CEnvScreenOverlay,
            CEnvTonemapController,
            CEnvWind,
            CFEPlayerDecal,
            CFireCrackerBlast,
            CFireSmoke,
            CFireTrail,
            CFish,
            CFists,
            CFlashbang,
            CFogController,
            CFootstepControl,
            CFunc_Dust,
            CFunc_LOD,
            CFuncAreaPortalWindow,
            CFuncBrush,
            CFuncConveyor,
            CFuncLadder,
            CFuncMonitor,
            CFuncMoveLinear,
            CFuncOccluder,
            CFuncReflectiveGlass,
            CFuncRotating,
            CFuncSmokeVolume,
            CFuncTrackTrain,
            CGameRulesProxy,
            CGrassBurn,
            CHandleTest,
            CHEGrenade,
            CHostage,
            CHostageCarriableProp,
            CIncendiaryGrenade,
            CInferno,
            CInfoLadderDismount,
            CInfoMapRegion,
            CInfoOverlayAccessor,
            CItem_Healthshot,
            CItemCash,
            CItemDogtags,
            CKnife,
            CKnifeGG,
            CLightGlow,
            CMaterialModifyControl,
            CMelee,
            CMolotovGrenade,
            CMolotovProjectile,
            CMovieDisplay,
            CParadropChopper,
            CParticleFire,
            CParticlePerformanceMonitor,
            CParticleSystem,
            CPhysBox,
            CPhysBoxMultiplayer,
            CPhysicsProp,
            CPhysicsPropMultiplayer,
            CPhysMagnet,
            CPhysPropAmmoBox,
            CPhysPropLootCrate,
            CPhysPropRadarJammer,
            CPhysPropWeaponUpgrade,
            CPlantedC4,
            CPlasma,
            CPlayerPing,
            CPlayerResource,
            CPointCamera,
            CPointCommentaryNode,
            CPointWorldText,
            CPoseController,
            CPostProcessController,
            CPrecipitation,
            CPrecipitationBlocker,
            CPredictedViewModel,
            CProp_Hallucination,
            CPropCounter,
            CPropDoorRotating,
            CPropJeep,
            CPropVehicleDriveable,
            CRagdollManager,
            CRagdollProp,
            CRagdollPropAttached,
            CRopeKeyframe,
            CSCAR17,
            CSceneEntity,
            CSensorGrenade,
            CSensorGrenadeProjectile,
            CShadowControl,
            CSlideshowDisplay,
            CSmokeGrenade,
            CSmokeGrenadeProjectile,
            CSmokeStack,
            CSnowball,
            CSnowballPile,
            CSnowballProjectile,
            CSpatialEntity,
            CSpotlightEnd,
            CSprite,
            CSpriteOriented,
            CSpriteTrail,
            CStatueProp,
            CSteamJet,
            CSun,
            CSunlightShadowControl,
            CSurvivalSpawnChopper,
            CTablet,
            CTeam,
            CTeamplayRoundBasedRulesProxy,
            CTEArmorRicochet,
            CTEBaseBeam,
            CTEBeamEntPoint,
            CTEBeamEnts,
            CTEBeamFollow,
            CTEBeamLaser,
            CTEBeamPoints,
            CTEBeamRing,
            CTEBeamRingPoint,
            CTEBeamSpline,
            CTEBloodSprite,
            CTEBloodStream,
            CTEBreakModel,
            CTEBSPDecal,
            CTEBubbles,
            CTEBubbleTrail,
            CTEClientProjectile,
            CTEDecal,
            CTEDust,
            CTEDynamicLight,
            CTEEffectDispatch,
            CTEEnergySplash,
            CTEExplosion,
            CTEFireBullets,
            CTEFizz,
            CTEFootprintDecal,
            CTEFoundryHelpers,
            CTEGaussExplosion,
            CTEGlowSprite,
            CTEImpact,
            CTEKillPlayerAttachments,
            CTELargeFunnel,
            CTEMetalSparks,
            CTEMuzzleFlash,
            CTEParticleSystem,
            CTEPhysicsProp,
            CTEPlantBomb,
            CTEPlayerAnimEvent,
            CTEPlayerDecal,
            CTEProjectedDecal,
            CTERadioIcon,
            CTEShatterSurface,
            CTEShowLine,
            CTesla,
            CTESmoke,
            CTESparks,
            CTESprite,
            CTESpriteSpray,
            CTest_ProxyToggle_Networkable,
            CTestTraceline,
            CTEWorldDecal,
            CTriggerPlayerMovement,
            CTriggerSoundOperator,
            CVGuiScreen,
            CVoteController,
            CWaterBullet,
            CWaterLODControl,
            CWeaponAug,
            CWeaponAWP,
            CWeaponBaseItem,
            CWeaponBizon,
            CWeaponCSBase,
            CWeaponCSBaseGun,
            CWeaponCycler,
            CWeaponElite,
            CWeaponFamas,
            CWeaponFiveSeven,
            CWeaponG3SG1,
            CWeaponGalil,
            CWeaponGalilAR,
            CWeaponGlock,
            CWeaponHKP2000,
            CWeaponM249,
            CWeaponM3,
            CWeaponM4A1,
            CWeaponMAC10,
            CWeaponMag7,
            CWeaponMP5Navy,
            CWeaponMP7,
            CWeaponMP9,
            CWeaponNegev,
            CWeaponNOVA,
            CWeaponP228,
            CWeaponP250,
            CWeaponP90,
            CWeaponSawedoff,
            CWeaponSCAR20,
            CWeaponScout,
            CWeaponSG550,
            CWeaponSG552,
            CWeaponSG556,
            CWeaponShield,
            CWeaponSSG08,
            CWeaponTaser,
            CWeaponTec9,
            CWeaponTMP,
            CWeaponUMP45,
            CWeaponUSP,
            CWeaponXM1014,
            CWorld,
            CWorldVguiText,
            DustTrail,
            MovieExplosion,
            ParticleSmokeGrenade,
            RocketTrail,
            SmokeTrail,
            SporeExplosion,
            SporeTrail
        };
    }
}
